name: flutter_piano
description: A piano app build in flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  tonic: ^0.2.3
  flutter_midi: ^0.1.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/sounds/Piano.sf2